name: example
description: A example of altive_lints.
publish_to: "none"
version: 1.0.0
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints:
    path: ..
